apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: consul-service-controller
  name: consul-service-controller
  namespace: gnossen-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: consul-service-controller
  name: gnossen-system:consul-service-controller-role
rules:
- apiGroups:
  - ''
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - services/status
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: consul-service-controller
  name: gnossen-system-system:consul-service-controller-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gnossen-system:consul-service-controller-role
subjects:
- kind: ServiceAccount
  name: consul-service-controller
  namespace: gnossen-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-service-controller
  namespace: gnossen-system
  labels:
    app: consul-service-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul-service-controller
  template:
    metadata:
      labels:
        app: consul-service-controller
    spec:
      serviceAccountName: consul-service-controller
      containers:
      - name: consul-service-controller
        image: docker:5000/consul-service-controller:1
        args:
        - "/consul_service_controller"
        - "--poll-seconds=60"
        - "--consul-endpoint=sidecar:8500"
        - "--max-consul-attempts=5"
        - "--attempt-wait-seconds=2"
